### ISSUE TITLE
Missing roots from the dictionary

### ISSUE THREAD

**Issue by Ykulvaarlck** [porpoiseless/ithkuil#1]
The dictionary seems to be missing the following roots, which in the lexicon had either the preceding or following hyphen missing:

- LC'
- KSP
- ŘThW
- ŘZW
- SQ

More roots could be missing if I missed any or if one of them misses hyphens on both sides, since I did not check for this kind of mistake. I suggest you detect roots by the `<strong>` tag, since they all seem to be written in bold.
![firefox_2017-09-24_21-23-56](https://user-images.githubusercontent.com/15966911/30785371-b6ff74cc-a16e-11e7-98f2-c0b06fab94d2.png)

**Comment by porpoiseless** [comment]
Thanks for this Ykul--an improved scraper based on this is in the works.
